spring.application.name=cea

spring.datasource.url=jdbc:mysql://localhost:3306/db_cea
spring.datasource.username=root
spring.datasource.password=jesus475

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.user.name=jesus
spring.security.user.password=12345